import os
import sys

def returnConfig(era):
    #----- Common -----#
    hists = {'HH_cat_ee_1b_jet1_pt' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_pt',
             'HH_cat_mm_1b_jet1_pt' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_pt',
             'HH_cat_em_1b_jet1_pt' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_pt',
             'HH_cat_ee_2b_jet1_pt' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_pt',
             'HH_cat_mm_2b_jet1_pt' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_pt',
             'HH_cat_em_2b_jet1_pt' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_pt',
             'HH_cat_ee_1b_lep1_pt' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_pt',
             'HH_cat_mm_1b_lep1_pt' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_pt',
             'HH_cat_em_1b_lep1_pt' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_pt',
             'HH_cat_ee_2b_lep1_pt' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_pt',
             'HH_cat_mm_2b_lep1_pt' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_pt',
             'HH_cat_em_2b_lep1_pt' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_pt',
             'HH_cat_ee_1b_jet1_eta' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_eta',
             'HH_cat_mm_1b_jet1_eta' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_eta',
             'HH_cat_em_1b_jet1_eta' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_eta',
             'HH_cat_ee_2b_jet1_eta' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_eta',
             'HH_cat_mm_2b_jet1_eta' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_eta',
             'HH_cat_em_2b_jet1_eta' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_eta',
             'HH_cat_ee_1b_lep1_eta' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_eta',
             'HH_cat_mm_1b_lep1_eta' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_eta',
             'HH_cat_em_1b_lep1_eta' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_eta',
             'HH_cat_ee_2b_lep1_eta' : 'ElEl_HasElElTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_eta',
             'HH_cat_mm_2b_lep1_eta' : 'MuMu_HasMuMuTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_eta',
             'HH_cat_em_2b_lep1_eta' : 'ElMu_HasElMuTightTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_eta',
             }

    #---- Per era -----#
    if era == "2016":
        path = '/home/ucl/cp3/fbury/bamboodev/HHbbWWAnalysis/BambooOutputHHtobbWW/full2016RatioFake_tight_nosyst/'
        yamlName = 'plots_FakeExtrapolation.yml'
        groups = {'TTZ':   ['TTZToQQ.root',
                            'TTZToLLNuNu.root'],
                  'TH' :   [],
                  'VH' :   ['HZJ_HToWW.root',
                            'ggZH_HToBB_ZToLL.root',
                            'ggZH_HToBB_ZToNuNu.root'],
                  'TT' :   ['TTTo2L2Nu.root',
                            'TTToSemiLeptonic.root',
                            'TTToHadronic.root',
                            'ST_tW_top_5f.root',
                            'ST_tW_antitop_5f.root',
                            'ST_tchannel_antitop_4f.root',
                            'ST_tchannel_top_4f.root'],
                  'TTW':   ['TTWJetsToQQ.root',
                            'TTWJetsToLNu.root'],
                  'WW' :   ['WWToLNuQQ.root',
                            'WWTo2L2Nu.root',
                            'WJetsToLNu.root'],
                  'TTH':   ['ttHTobb.root',
                            'ttHToNonbb.root'],
                  'ZZ' :   ['ZZTo2L2Nu.root',
                            'ZZTo2L2Q.root',
                            'ZZTo4L.root'],
                  'DY' :   ['DYJetsToLL_M-10to50.root',
                            'DYToLL_0J.root',
                            'DYToLL_1J.root',
                            'DYToLL_2J.root'],
                  'Other': ['WWW.root',
                            'WWZ.root',
                            'WZZ.root',
                            'ZZZ.root'],
                  'WZ' :   ['WZTo2L2Q.root',
                            'WZTo1L3Nu.root',
                            'WZ1L1Nu2Q.root',
                            'WZ1L1Nu2Q.root',
                            'WZTo3LNu.root'],
                  'TTWW' : [],
                  'data_fake': ['DoubleEGamma_2016BFakeExtrapolation.',
                                'DoubleEGamma_2016CFakeExtrapolation.',
                                'DoubleEGamma_2016DFakeExtrapolation.',
                                'DoubleEGamma_2016EFakeExtrapolation.',
                                'DoubleEGamma_2016FFakeExtrapolation.',
                                'DoubleEGamma_2016GFakeExtrapolation.',
                                'DoubleEGamma_2016HFakeExtrapolation.',
                                'DoubleMuon_2016BFakeExtrapolation.',
                                'DoubleMuon_2016CFakeExtrapolation.',
                                'DoubleMuon_2016DFakeExtrapolation.',
                                'DoubleMuon_2016EFakeExtrapolation.',
                                'DoubleMuon_2016FFakeExtrapolation.',
                                'DoubleMuon_2016GFakeExtrapolation.',
                                'DoubleMuon_2016HFakeExtrapolation.',
                                'DYJetsToLL_M-10to50FakeExtrapolation.',
                                'DYJetsToLL_M-50FakeExtrapolation.',
                                'DYToLL_0JFakeExtrapolation.',
                                'DYToLL_1JFakeExtrapolation.',
                                'DYToLL_2JFakeExtrapolation.',
                                'GluGluHToBBFakeExtrapolation.',
                                'GluGluHToGGFakeExtrapolation.',
                                'GluGluHToMuMuFakeExtrapolation.',
                                'GluGluHToTauTauFakeExtrapolation.',
                                'GluGluHToWWTo2L2NuFakeExtrapolation.',
                                'GluGluHToWWToLNuQQFakeExtrapolation.',
                                'GluGluHToZZTo4LFakeExtrapolation.',
                                'HZJ_HToWWFakeExtrapolation.',
                                'MuonEG_2016BFakeExtrapolation.',
                                'MuonEG_2016CFakeExtrapolation.',
                                'MuonEG_2016DFakeExtrapolation.',
                                'MuonEG_2016EFakeExtrapolation.',
                                'MuonEG_2016FFakeExtrapolation.',
                                'MuonEG_2016GFakeExtrapolation.',
                                'MuonEG_2016HFakeExtrapolation.',
                                'SingleElectron_2016BFakeExtrapolation.',
                                'SingleElectron_2016CFakeExtrapolation.',
                                'SingleElectron_2016DFakeExtrapolation.',
                                'SingleElectron_2016EFakeExtrapolation.',
                                'SingleElectron_2016FFakeExtrapolation.',
                                'SingleElectron_2016GFakeExtrapolation.',
                                'SingleElectron_2016HFakeExtrapolation.',
                                'SingleMuon_2016BFakeExtrapolation.',
                                'SingleMuon_2016CFakeExtrapolation.',
                                'SingleMuon_2016DFakeExtrapolation.',
                                'SingleMuon_2016EFakeExtrapolation.',
                                'SingleMuon_2016FFakeExtrapolation.',
                                'SingleMuon_2016GFakeExtrapolation.',
                                'SingleMuon_2016HFakeExtrapolation.',
                                'ST_schannel_4fFakeExtrapolation.',
                                'ST_tchannel_antitop_4fFakeExtrapolation.',
                                'ST_tchannel_top_4fFakeExtrapolation.',
                                'ST_tW_antitop_5fFakeExtrapolation.',
                                'ST_tWll_5fFakeExtrapolation.',
                                'ST_tW_top_5fFakeExtrapolation.',
                                'TGJetsFakeExtrapolation.',
                                'TTGJetsFakeExtrapolation.',
                                'TTTo2L2NuFakeExtrapolation.',
                                'TTToHadronicFakeExtrapolation.',
                                'TTToSemiLeptonicFakeExtrapolation.',
                                'TTTTFakeExtrapolation.',
                                'TTWJetsToLNuFakeExtrapolation.',
                                'TTWJetsToQQFakeExtrapolation.',
                                'TTWWFakeExtrapolation.',
                                'TTZToLL_M-1to10FakeExtrapolation.',
                                'TTZToLLNuNu_M-10FakeExtrapolation.',
                                'TTZToQQFakeExtrapolation.',
                                'tZq_llFakeExtrapolation.',
                                'VBFHToBBFakeExtrapolation.',
                                'VBFHToGGFakeExtrapolation.',
                                'VBFHToMuMuFakeExtrapolation.',
                                'VBFHToTauTauFakeExtrapolation.',
                                'VBFHToWWTo2L2NuFakeExtrapolation.',
                                'VBFHToWWToLNuQQFakeExtrapolation.',
                                'VBF_HToZZTo4LFakeExtrapolation.',
                                'VHToNonbbFakeExtrapolation.',
                                'WGToLNuGFakeExtrapolation.',
                                'WJetsToLNuFakeExtrapolation.',
                                'WminusH_HToBB_WToLNuFakeExtrapolation.',
                                'WplusH_HToBB_WToLNuFakeExtrapolation.',
                                'WpWpJJFakeExtrapolation.',
                                'WWTo2L2Nu_DoubleScatteringFakeExtrapolation.',
                                'WWTo2L2NuFakeExtrapolation.',
                                'WWWFakeExtrapolation.',
                                'WWZFakeExtrapolation.',
                                'WZGFakeExtrapolation.',
                                'WZTo2L2QFakeExtrapolation.',
                                'WZTo3LNuFakeExtrapolation.',
                                'WZZFakeExtrapolation.',
                                'ZGTo2LGFakeExtrapolation.',
                                'ZH_HToBB_ZToLLFakeExtrapolation.',
                                'ZHToTauTauFakeExtrapolation.',
                                'ZZTo2L2QFakeExtrapolation.',
                                'ZZTo4LFakeExtrapolation.',
                                'ZZZFakeExtrapolation.',

                  'data_obs' : ['DoubleEGamma_2016B.root',
                                'DoubleEGamma_2016C.root',
                                'DoubleEGamma_2016D.root',
                                'DoubleEGamma_2016E.root',
                                'DoubleEGamma_2016F.root',
                                'DoubleEGamma_2016G.root',
                                'DoubleEGamma_2016H.root',
                                'DoubleMuon_2016B.root',
                                'DoubleMuon_2016C.root',
                                'DoubleMuon_2016D.root',
                                'DoubleMuon_2016E.root',
                                'DoubleMuon_2016F.root',
                                'DoubleMuon_2016G.root',
                                'DoubleMuon_2016H.root',
                                'MuonEG_2016B.root',
                                'MuonEG_2016C.root',
                                'MuonEG_2016D.root',
                                'MuonEG_2016E.root',
                                'MuonEG_2016F.root',
                                'MuonEG_2016G.root',
                                'MuonEG_2016H.root',
                                'SingleElectron_2016B.root',
                                'SingleElectron_2016C.root',
                                'SingleElectron_2016D.root',
                                'SingleElectron_2016E.root',
                                'SingleElectron_2016F.root',
                                'SingleElectron_2016G.root',
                                'SingleElectron_2016H.root',
                                'SingleMuon_2016B.root',
                                'SingleMuon_2016C.root',
                                'SingleMuon_2016D.root',
                                'SingleMuon_2016E.root',
                                'SingleMuon_2016F.root',
                                'SingleMuon_2016G.root',
                                'SingleMuon_2016H.root']}    
        return [path,yamlName,groups,hists]

    if era == '2017':
        path = '/home/ucl/cp3/fbury/bamboodev/HHbbWWAnalysis/BambooOutputHHtobbWW/full2017RatioFake_tight_nosyst/'
        yamlName = 'plots_FakeExtrapolation.yml'
        groups = {'TTZ':   ['TTZToQQ.root','TTZToLLNuNu.root'],
                  'TH' :   [],
                  'VH' :   ['HZJ_HToWW.root',
                            'ggZH_HToBB_ZToLL.root',
                            'ggZH_HToBB_ZToNuNu.root'],
                  'TT' :   ['TTTo2L2Nu.root',
                            'TTToSemiLeptonic.root',
                            'TTToHadronic.root',
                            'ST_tW_top_5f.root',
                            'ST_tW_antitop_5f.root',
                            'ST_tchannel_antitop_4f.root',
                            'ST_tchannel_top_4f.root'],
                  'TTW':   ['TTWJetsToQQ.root',
                            'TTWJetsToLNu.root'],
                  'WW' :   ['WWToLNuQQ.root',
                            'WWTo2L2Nu.root',
                            'WJetsToLNu.root'],
                  'TTH':   ['ttHTobb.root',
                            'ttHToNonbb.root'],
                  'ZZ' :   ['ZZTo2L2Nu.root',
                            'ZZTo2L2Q.root',
                            'ZZTo4L.root'],
                  'DY' :   ['DYJetsToLL_M-10to50.root',
                            'DYJetsToLL_0J.root',
                            'DYJetsToLL_1J.root',
                            'DYJetsToLL_2J.root'],
                  'Other': ['WWW.root',
                            'WWZ.root',
                            'WZZ.root',
                            'ZZZ.root'],
                  'WZ' :   ['WZTo2L2Q.root',
                            'WZTo1L3Nu.root',
                            'WZ1L1Nu2Q.root',
                            'WZ1L1Nu2Q.root',
                            'WZTo3LNu.root'],
                  'TTWW' : [],
                  'data_fake': ['DYJetsToLL_0JFakeExtrapolation.root',
                                'DYJetsToLL_1JFakeExtrapolation.root',
                                'DYJetsToLL_2JFakeExtrapolation.root',
                                'DYJetsToLL_M-10to50FakeExtrapolation.root',
                                'ggZH_HToBB_ZToLLFakeExtrapolation.root',
                                'HZJ_HToWWFakeExtrapolation.root',
                                'ST_tchannel_antitop_4fFakeExtrapolation.root',
                                'ST_tchannel_top_4fFakeExtrapolation.root',
                                'ST_tW_antitop_5fFakeExtrapolation.root',
                                'ST_tW_top_5fFakeExtrapolation.root',
                                'ttHTobbFakeExtrapolation.root',
                                'ttHToNonbbFakeExtrapolation.root',
                                'TTTo2L2NuFakeExtrapolation.root',
                                'TTToHadronicFakeExtrapolation.root',
                                'TTToSemiLeptonicFakeExtrapolation.root',
                                'TTWJetsToLNuFakeExtrapolation.root',
                                'TTWJetsToQQFakeExtrapolation.root',
                                'TTZToLLNuNuFakeExtrapolation.root',
                                'TTZToQQFakeExtrapolation.root',
                                'WJetsToLNuFakeExtrapolation.root',
                                'WWTo2L2NuFakeExtrapolation.root',
                                'WWToLNuQQFakeExtrapolation.root',
                                'WWWFakeExtrapolation.root',
                                'WWZFakeExtrapolation.root',
                                'WZ1L1Nu2QFakeExtrapolation.root',
                                'WZTo1L3NuFakeExtrapolation.root',
                                'WZTo2L2QFakeExtrapolation.root',
                                'WZTo3LNuFakeExtrapolation.root',
                                'WZZFakeExtrapolation.root',
                                'ZZTo2L2NuFakeExtrapolation.root',
                                'ZZTo2L2QFakeExtrapolation.root',
                                'ZZTo4LFakeExtrapolation.root',
                                'ZZZFakeExtrapolation.root',
                                'DoubleEGamma_2017BFakeExtrapolation.root',
                                'DoubleEGamma_2017CFakeExtrapolation.root',
                                'DoubleEGamma_2017DFakeExtrapolation.root',
                                'DoubleEGamma_2017EFakeExtrapolation.root',
                                'DoubleEGamma_2017FFakeExtrapolation.root',
                                'DoubleMuon_2017BFakeExtrapolation.root',
                                'DoubleMuon_2017CFakeExtrapolation.root',
                                'DoubleMuon_2017DFakeExtrapolation.root',
                                'DoubleMuon_2017EFakeExtrapolation.root',
                                'DoubleMuon_2017FFakeExtrapolation.root',
                                'MuonEG_2017BFakeExtrapolation.root',
                                'MuonEG_2017CFakeExtrapolation.root',
                                'MuonEG_2017DFakeExtrapolation.root',
                                'MuonEG_2017EFakeExtrapolation.root',
                                'MuonEG_2017FFakeExtrapolation.root',
                                'SingleElectron_2017BFakeExtrapolation.root',
                                'SingleElectron_2017CFakeExtrapolation.root',
                                'SingleElectron_2017DFakeExtrapolation.root',
                                'SingleElectron_2017EFakeExtrapolation.root',
                                'SingleElectron_2017FFakeExtrapolation.root',
                                'SingleMuon_2017BFakeExtrapolation.root',
                                'SingleMuon_2017CFakeExtrapolation.root',
                                'SingleMuon_2017DFakeExtrapolation.root',
                                'SingleMuon_2017EFakeExtrapolation.root',
                                'SingleMuon_2017FFakeExtrapolation.root'],

                  'data_obs' : ['DoubleEGamma_2017B.root',
                                'DoubleEGamma_2017C.root',
                                'DoubleEGamma_2017D.root',
                                'DoubleEGamma_2017E.root',
                                'DoubleEGamma_2017F.root',
                                'DoubleMuon_2017B.root',
                                'DoubleMuon_2017C.root',
                                'DoubleMuon_2017D.root',
                                'DoubleMuon_2017E.root',
                                'DoubleMuon_2017F.root',
                                'MuonEG_2017B.root',
                                'MuonEG_2017C.root',
                                'MuonEG_2017D.root',
                                'MuonEG_2017E.root',
                                'MuonEG_2017F.root',
                                'SingleElectron_2017B.root',
                                'SingleElectron_2017C.root',
                                'SingleElectron_2017D.root',
                                'SingleElectron_2017E.root',
                                'SingleElectron_2017F.root',
                                'SingleMuon_2017B.root',
                                'SingleMuon_2017C.root',
                                'SingleMuon_2017D.root',
                                'SingleMuon_2017E.root',
                                'SingleMuon_2017F.root']}    
        return [path,yamlName,groups,hists]

    if era == '2018':
        path = '/home/ucl/cp3/fbury/bamboodev/HHbbWWAnalysis/BambooOutputHHtobbWW/full2018RatioFake_tight_nosyst/'
        yamlName = 'plots_FakeExtrapolation.yml'
        groups = {'TTZ':   ['TTZToQQ.root','TTZToLLNuNu.root'],
                  'TH' :   [],
                  'VH' :   ['HZJ_HToWW.root',
                            'ggZH_HToBB_ZToLL.root',
                            'ggZH_HToBB_ZToNuNu.root'],
                  'TT' :   ['TTTo2L2Nu.root',
                            'TTToSemiLeptonic.root',
                            'TTToHadronic.root',
                            'ST_tW_top_5f.root',
                            'ST_tW_antitop_5f.root',
                            'ST_tchannel_antitop_4f.root',
                            'ST_tchannel_top_4f.root'],
                  'TTW':   ['TTWJetsToQQ.root',
                            'TTWJetsToLNu.root'],
                  'WW' :   ['WWToLNuQQ.root',
                            'WWTo2L2Nu.root',
                            'WJetsToLNu.root'],
                  'TTH':   ['ttHTobb.root',
                            'ttHToNonbb.root'],
                  'ZZ' :   ['ZZTo2L2Nu.root',
                            'ZZTo2L2Q.root',
                            'ZZTo4L.root'],
                  'DY' :   ['DYJetsToLL_M-10to50.root',
                            'DYJetsToLL_0J.root',
                            'DYJetsToLL_1J.root',
                            'DYJetsToLL_2J.root'],
                  'Other': ['WWW.root',
                            'WWZ.root',
                            'WZZ.root',
                            'ZZZ.root'],
                  'WZ' :   ['WZTo2L2Q.root',
                            'WZTo1L3Nu.root',
                            'WZ1L1Nu2Q.root',
                            'WZ1L1Nu2Q.root',
                            'WZTo3LNu.root',
                            'WZTo1L1Nu2Q.root'],
                  'TTWW' : [],
                  'data_fake': ['DYJetsToLL_0JFakeExtrapolation.root',
                                'DYJetsToLL_1JFakeExtrapolation.root',
                                'DYJetsToLL_2JFakeExtrapolation.root',
                                'DYJetsToLL_M-10to50FakeExtrapolation.root',
                                'ggZH_HToBB_ZToLLFakeExtrapolation.root',
                                'ggZH_HToBB_ZToNuNuFakeExtrapolation.root',
                                'HZJ_HToWWFakeExtrapolation.root',
                                'ST_tchannel_antitop_4fFakeExtrapolation.root',
                                'ST_tchannel_top_4fFakeExtrapolation.root',
                                'ST_tW_antitop_5fFakeExtrapolation.root',
                                'ST_tW_top_5fFakeExtrapolation.root',
                                'ttHTobbFakeExtrapolation.root',
                                'ttHToNonbbFakeExtrapolation.root',
                                'TTTo2L2NuFakeExtrapolation.root',
                                'TTToHadronicFakeExtrapolation.root',
                                'TTToSemiLeptonicFakeExtrapolation.root',
                                'TTWJetsToLNuFakeExtrapolation.root',
                                'TTWJetsToQQFakeExtrapolation.root',
                                'TTZToLLNuNuFakeExtrapolation.root',
                                'TTZToQQFakeExtrapolation.root',
                                'WJetsToLNuFakeExtrapolation.root',
                                'WWTo2L2NuFakeExtrapolation.root',
                                'WWToLNuQQFakeExtrapolation.root',
                                'WWWFakeExtrapolation.root',
                                'WWZFakeExtrapolation.root',
                                'WZTo1L1Nu2QFakeExtrapolation.root',
                                'WZTo1L3NuFakeExtrapolation.root',
                                'WZTo2L2QFakeExtrapolation.root',
                                'WZTo3LNuFakeExtrapolation.root',
                                'WZZFakeExtrapolation.root',
                                'ZZTo2L2NuFakeExtrapolation.root',
                                'ZZTo2L2QFakeExtrapolation.root',
                                'ZZTo4LFakeExtrapolation.root',
                                'ZZZFakeExtrapolation.root',
                                'DoubleMuon_2018AFakeExtrapolation.root',
                                'DoubleMuon_2018BFakeExtrapolation.root',
                                'DoubleMuon_2018CFakeExtrapolation.root',
                                'DoubleMuon_2018DFakeExtrapolation.root',
                                'SingleMuon_2018AFakeExtrapolation.root',
                                'SingleMuon_2018BFakeExtrapolation.root',
                                'SingleMuon_2018CFakeExtrapolation.root',
                                'SingleMuon_2018DFakeExtrapolation.root',
                                'MuonEG_2018AFakeExtrapolation.root',
                                'MuonEG_2018BFakeExtrapolation.root',
                                'MuonEG_2018CFakeExtrapolation.root',
                                'MuonEG_2018DFakeExtrapolation.root',
                                'EGamma_2018AFakeExtrapolation.root',
                                'EGamma_2018BFakeExtrapolation.root',
                                'EGamma_2018CFakeExtrapolation.root',
                                'EGamma_2018DFakeExtrapolation.root'],
                  'data_obs' : ['DoubleMuon_2018A.root',
                                'DoubleMuon_2018B.root',
                                'DoubleMuon_2018C.root',
                                'DoubleMuon_2018D.root',
                                'SingleMuon_2018A.root',
                                'SingleMuon_2018B.root',
                                'SingleMuon_2018C.root',
                                'SingleMuon_2018D.root',
                                'MuonEG_2018A.root',
                                'MuonEG_2018B.root',
                                'MuonEG_2018C.root',
                                'MuonEG_2018D.root',
                                'EGamma_2018A.root',
                                'EGamma_2018B.root',
                                'EGamma_2018C.root',
                                'EGamma_2018D.root']}    

        return [path,yamlName,groups,hists]

def returnZPeakConfig(era):
    #----- Common -----#
    hists = {'HH_cat_ee_0b_jet1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_leadjet_pt',
             'HH_cat_ee_1b_jet1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_pt',
             'HH_cat_ee_2b_jet1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_pt',
             'HH_cat_ee_0b_lep1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_firstlepton_pt',
             'HH_cat_ee_1b_lep1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_pt',
             'HH_cat_ee_2b_lep1_pt' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_pt',
             'HH_cat_ee_0b_jet1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_leadjet_eta',
             'HH_cat_ee_1b_jet1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_eta',
             'HH_cat_ee_2b_jet1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_eta',
             'HH_cat_ee_0b_lep1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_firstlepton_eta',
             'HH_cat_ee_1b_lep1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_eta',
             'HH_cat_ee_2b_lep1_eta' : 'ElEl_HasElElTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_eta',
             'HH_cat_mm_0b_jet1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_leadjet_pt',
             'HH_cat_mm_1b_jet1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_pt',
             'HH_cat_mm_2b_jet1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_pt',
             'HH_cat_mm_0b_lep1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_firstlepton_pt',
             'HH_cat_mm_1b_lep1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_pt',
             'HH_cat_mm_2b_lep1_pt' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_pt',
             'HH_cat_mm_0b_jet1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_leadjet_eta',
             'HH_cat_mm_1b_jet1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_leadbjet_eta',
             'HH_cat_mm_2b_jet1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_leadbjet_eta',
             'HH_cat_mm_0b_lep1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedNoBtag_firstlepton_eta',
             'HH_cat_mm_1b_lep1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedOneBtag_firstlepton_eta',
             'HH_cat_mm_2b_lep1_eta' : 'MuMu_HasMuMuTightZPeakTwoAk4JetsExclusiveResolvedTwoBtags_firstlepton_eta',
                    }
    path = '/home/ucl/cp3/fbury/bamboodev/HHbbWWAnalysis/BambooOutputHHtobbWW/full2016RatioFake_tight_ZPeak_nosyst/'
    yamlName = 'plots_FakeExtrapolation.yml'
    groups = {'TTZ':   ['TTZToQQ.root','TTZToLLNuNu.root'],
              'TH' :   [],
              'VH' :   ['HZJ_HToWW.root',
                        'ggZH_HToBB_ZToLL.root',
                        'ggZH_HToBB_ZToNuNu.root'],
              'TT' :   ['TTTo2L2Nu.root',
                        'TTToSemiLeptonic.root',
                        'TTToHadronic.root',
                        'ST_tW_top_5f.root',
                        'ST_tW_antitop_5f.root',
                        'ST_tchannel_antitop_4f.root',
                        'ST_tchannel_top_4f.root'],
              'TTW':   ['TTWJetsToQQ.root',
                        'TTWJetsToLNu.root'],
              'WW' :   ['WWToLNuQQ.root',
                        'WWTo2L2Nu.root',
                        'WJetsToLNu.root'],
              'TTH':   ['ttHTobb.root',
                        'ttHToNonbb.root'],
              'ZZ' :   ['ZZTo2L2Nu.root',
                        'ZZTo2L2Q.root',
                        'ZZTo4L.root'],
              'DY' :   ['DYJetsToLL_M-10to50.root',
                        'DYToLL_0J.root',
                        'DYToLL_1J.root',
                        'DYToLL_2J.root'],
              'Other': ['WWW.root',
                        'WWZ.root',
                        'WZZ.root',
                        'ZZZ.root'],
              'WZ' :   ['WZTo2L2Q.root',
                        'WZTo1L3Nu.root',
                        'WZ1L1Nu2Q.root',
                        'WZ1L1Nu2Q.root',
                        'WZTo3LNu.root'],
              'TTWW' : [],
              'data_fake': ['DYToLL_0JFakeExtrapolation.root',
                            'DYToLL_1JFakeExtrapolation.root',
                            'DYToLL_2JFakeExtrapolation.root',
                            'ggZH_HToBB_ZToLLFakeExtrapolation.root',
                            'ggZH_HToBB_ZToNuNuFakeExtrapolation.root',
                            'HZJ_HToWWFakeExtrapolation.root',
                            'ST_tchannel_antitop_4fFakeExtrapolation.root',
                            'ST_tchannel_top_4fFakeExtrapolation.root',
                            'ST_tW_antitop_5fFakeExtrapolation.root',
                            'ST_tW_top_5fFakeExtrapolation.root',
                            'ttHTobbFakeExtrapolation.root',
                            'ttHToNonbbFakeExtrapolation.root',
                            'TTTo2L2NuFakeExtrapolation.root',
                            'TTToHadronicFakeExtrapolation.root',
                            'TTToSemiLeptonicFakeExtrapolation.root',
                            'TTWJetsToLNuFakeExtrapolation.root',
                            'TTWJetsToQQFakeExtrapolation.root',
                            'TTZToLLNuNuFakeExtrapolation.root',
                            'TTZToQQFakeExtrapolation.root',
                            'WJetsToLNuFakeExtrapolation.root',
                            'WWTo2L2NuFakeExtrapolation.root',
                            'WWToLNuQQFakeExtrapolation.root',
                            'WWWFakeExtrapolation.root',
                            'WWZFakeExtrapolation.root',
                            'WZ1L1Nu2QFakeExtrapolation.root',
                            'WZTo1L3NuFakeExtrapolation.root',
                            'WZTo2L2QFakeExtrapolation.root',
                            'WZTo3LNuFakeExtrapolation.root',
                            'WZZFakeExtrapolation.root',
                            'ZZTo2L2NuFakeExtrapolation.root',
                            'ZZTo2L2QFakeExtrapolation.root',
                            'ZZTo4LFakeExtrapolation.root',
                            'ZZZFakeExtrapolation.root',
                            'DoubleEGamma_2016BFakeExtrapolation.root',
                            'DoubleEGamma_2016CFakeExtrapolation.root',
                            'DoubleEGamma_2016DFakeExtrapolation.root',
                            'DoubleEGamma_2016EFakeExtrapolation.root',
                            'DoubleEGamma_2016FFakeExtrapolation.root',
                            'DoubleEGamma_2016GFakeExtrapolation.root',
                            'DoubleEGamma_2016HFakeExtrapolation.root',
                            'DoubleMuon_2016BFakeExtrapolation.root',
                            'DoubleMuon_2016CFakeExtrapolation.root',
                            'DoubleMuon_2016DFakeExtrapolation.root',
                            'DoubleMuon_2016EFakeExtrapolation.root',
                            'DoubleMuon_2016FFakeExtrapolation.root',
                            'DoubleMuon_2016GFakeExtrapolation.root',
                            'DoubleMuon_2016HFakeExtrapolation.root',
                            'DYJetsToLL_M-10to50FakeExtrapolation.root',
                            'MuonEG_2016BFakeExtrapolation.root',
                            'MuonEG_2016CFakeExtrapolation.root',
                            'MuonEG_2016DFakeExtrapolation.root',
                            'MuonEG_2016EFakeExtrapolation.root',
                            'MuonEG_2016FFakeExtrapolation.root',
                            'MuonEG_2016GFakeExtrapolation.root',
                            'MuonEG_2016HFakeExtrapolation.root',
                            'SingleElectron_2016BFakeExtrapolation.root',
                            'SingleElectron_2016CFakeExtrapolation.root',
                            'SingleElectron_2016DFakeExtrapolation.root',
                            'SingleElectron_2016EFakeExtrapolation.root',
                            'SingleElectron_2016FFakeExtrapolation.root',
                            'SingleElectron_2016GFakeExtrapolation.root',
                            'SingleElectron_2016HFakeExtrapolation.root',
                            'SingleMuon_2016BFakeExtrapolation.root',
                            'SingleMuon_2016CFakeExtrapolation.root',
                            'SingleMuon_2016DFakeExtrapolation.root',
                            'SingleMuon_2016EFakeExtrapolation.root',
                            'SingleMuon_2016FFakeExtrapolation.root',
                            'SingleMuon_2016GFakeExtrapolation.root',
                            'SingleMuon_2016HFakeExtrapolation.root'],
              'data_obs' : ['DoubleEGamma_2016B.root',
                            'DoubleEGamma_2016C.root',
                            'DoubleEGamma_2016D.root',
                            'DoubleEGamma_2016E.root',
                            'DoubleEGamma_2016F.root',
                            'DoubleEGamma_2016G.root',
                            'DoubleEGamma_2016H.root',
                            'DoubleMuon_2016B.root',
                            'DoubleMuon_2016C.root',
                            'DoubleMuon_2016D.root',
                            'DoubleMuon_2016E.root',
                            'DoubleMuon_2016F.root',
                            'DoubleMuon_2016G.root',
                            'DoubleMuon_2016H.root',
                            'MuonEG_2016B.root',
                            'MuonEG_2016C.root',
                            'MuonEG_2016D.root',
                            'MuonEG_2016E.root',
                            'MuonEG_2016F.root',
                            'MuonEG_2016G.root',
                            'MuonEG_2016H.root',
                            'SingleElectron_2016B.root',
                            'SingleElectron_2016C.root',
                            'SingleElectron_2016D.root',
                            'SingleElectron_2016E.root',
                            'SingleElectron_2016F.root',
                            'SingleElectron_2016G.root',
                            'SingleElectron_2016H.root',
                            'SingleMuon_2016B.root',
                            'SingleMuon_2016C.root',
                            'SingleMuon_2016D.root',
                            'SingleMuon_2016E.root',
                            'SingleMuon_2016F.root',
                            'SingleMuon_2016G.root',
                            'SingleMuon_2016H.root']}    
    return [path,yamlName,groups,hists]


